version: '3.8'

services:
  web:
    build: .
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    env_file:
      - app/.env
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    ports:
      - 5432:5432


volumes:
  postgres_data_prod:
