upstream api_server{
    server web:80;
}
server {
    client_max_body_size 5M;  

    listen 80;

    error_page 413 = @handle_413;

    location @handle_413 {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
        add_header 'Access-Control-Max-Age' 1728000 always;
        default_type application/json; 
        
        return 413 '{"error": "Request Entity Too Large", "status": 413}';
    }

    server_name localhost;

    location / {
        proxy_pass http://api_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
	    proxy_set_header Referer $http_referer;
    }
}
