upstream api_server{
    server web:80;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    server_name _;  
    
    return 444;
}

server {
    listen 80;

    server_name valetiny-postcard-api.24-7.ro;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://valetiny-postcard-api.24-7.ro$request_uri;
    }
}

server {
    listen 443 default_server ssl;                            
    listen [::]:443 ssl;

    server_name valetiny-postcard-api.24-7.ro;


    client_max_body_size 5M;  


    error_page 413 = @handle_413;

    location @handle_413 {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
        add_header 'Access-Control-Max-Age' 1728000 always;
        default_type application/json; 
        
        return 413 '{"error": "Request Entity Too Large", "status": 413}';
    }

    ssl_certificate "/etc/nginx/ssl/live/valetiny-postcard-api.24-7.ro/fullchain.pem";
    ssl_certificate_key "/etc/nginx/ssl/live/valetiny-postcard-api.24-7.ro/privkey.pem";

    location / {
        proxy_pass http://api_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
	    proxy_set_header Referer $http_referer;
    }
}
